--- #YAML:1.0
name:               App-IsGitSynced
version:            0.01
abstract:           script to find out if the local git repo is fully synced
author:
    - Ivan Bessarabov <ivan@bessarabov.ru>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Test::More:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
